"""
Invoice and Receipt Routes
Provides endpoints for generating and viewing professional invoices
"""

from flask import Blueprint, render_template, jsonify, request, send_file, current_app
from flask_login import current_user
from datetime import datetime, timedelta
from io import BytesIO
import json
from app.models import db, Setting, Company

# Create blueprint
invoices_bp = Blueprint('invoices', __name__, url_prefix='/invoices', template_folder='templates')


def get_receipt_settings(company_id=None):
    """Get receipt settings from database, with fallback defaults"""
    try:
        # Get company_id if not provided
        if not company_id:
            try:
                if current_user.is_authenticated:
                    from app.utils.company import get_current_company
                    company = get_current_company()
                    company_id = company.id if company else None
            except Exception as e:
                current_app.logger.warning(f"Could not get current company: {str(e)}")
                company_id = None
        
        current_app.logger.info(f"[get_receipt_settings] Looking up settings for company_id: {company_id}")
        
        settings_dict = {}
        
        # PRIORITY 1: If company_id is provided, get company-specific settings FIRST
        if company_id:
            company_settings = Setting.query.filter_by(
                setting_category='receipt',
                company_id=company_id
            ).all()
            
            current_app.logger.info(f"[get_receipt_settings] Found {len(company_settings)} company-specific settings for company {company_id}")
            
            for setting in company_settings:
                settings_dict[setting.setting_key] = setting.setting_value
                current_app.logger.debug(f"  - {setting.setting_key} = {setting.setting_value}")
        
        # PRIORITY 2: Fall back to global settings (company_id = None) for missing keys only
        if settings_dict:
            # Company has some settings, just fill in gaps with global
            global_settings = Setting.query.filter_by(
                setting_category='receipt',
                company_id=None
            ).all()
            
            current_app.logger.info(f"[get_receipt_settings] Found {len(global_settings)} global settings for fallback")
            
            for setting in global_settings:
                if setting.setting_key not in settings_dict:
                    settings_dict[setting.setting_key] = setting.setting_value
        else:
            # No company settings found, use all global settings
            global_settings = Setting.query.filter_by(
                setting_category='receipt',
                company_id=None
            ).all()
            
            current_app.logger.info(f"[get_receipt_settings] No company settings found, using {len(global_settings)} global settings")
            
            for setting in global_settings:
                settings_dict[setting.setting_key] = setting.setting_value
        
        # Debug logging
        current_app.logger.info(f"Final settings_dict keys: {list(settings_dict.keys())}")
        
        # Merge with defaults
        business_name_value = settings_dict.get('business_name') or settings_dict.get('company_name', 'YOUR STORE')
        defaults = {
            'business_name': business_name_value,  # Direct key for templates
            'company_name': business_name_value,   # Alias for backwards compatibility
            'business_address': settings_dict.get('business_address', '123 Main Street, Suite 100'),
            'business_city': settings_dict.get('business_city', 'New York, NY 10001'),
            'business_phone': settings_dict.get('business_phone', 'Tel: (555) 123-4567'),
            'business_email': settings_dict.get('business_email', 'support@store.com'),
            'business_gst': settings_dict.get('business_gst', ''),
            'thank_you_message': settings_dict.get('thank_you_message', 'THANK YOU! For your patronage and support'),
            'warranty_info': settings_dict.get('warranty_info', 'Standard warranty: 1 year'),
            'footer_text': settings_dict.get('footer_text', 'Generated by POS System'),
            'receipt_logo': settings_dict.get('receipt_logo', ''),
            'default_receipt_format': settings_dict.get('default_receipt_format', 'thermal'),
            'show_qr_code': settings_dict.get('show_qr_code', 'true').lower() == 'true' if isinstance(settings_dict.get('show_qr_code'), str) else settings_dict.get('show_qr_code', True),
            'receipt_type': settings_dict.get('receipt_type', 'thermal'),
        }
        
        current_app.logger.info(f"Returning receipt settings: business_name={defaults['business_name']}, footer_text={defaults['footer_text']}")
        return defaults
    
    except Exception as e:
        current_app.logger.error(f"Error getting receipt settings: {str(e)}", exc_info=True)
        return get_default_receipt_settings()


def get_default_receipt_settings():
    """Get default receipt settings"""
    return {
        'company_name': 'YOUR STORE',
        'business_address': '123 Main Street, Suite 100',
        'business_city': 'New York, NY 10001',
        'business_phone': 'Tel: (555) 123-4567',
        'business_email': 'support@store.com',
        'business_gst': '',
        'thank_you_message': 'THANK YOU! For your patronage and support',
        'warranty_info': 'Standard warranty: 1 year',
        'footer_text': 'Generated by POS System',
        'receipt_logo': '',
        'default_receipt_format': 'thermal',
        'show_qr_code': True,
        'receipt_type': 'thermal',
    }


@invoices_bp.route('/preview/a4', methods=['GET'])
def preview_a4_invoice():
    """Preview A4 invoice template with sample data"""
    settings = get_receipt_settings()
    
    sample_data = {
        'invoice_number': 'INV-2026-001234',
        'invoice_date': datetime.now().strftime('%m/%d/%Y'),
        'due_date': (datetime.now() + timedelta(days=30)).strftime('%m/%d/%Y'),
        'status': 'UNPAID',
        'company': {
            'logo': 'LOGO',
            'name': settings['company_name'],
            'address': settings['business_address'],
            'city': settings['business_city'],
            'phone': settings['business_phone'],
            'email': settings['business_email'],
            'website': 'www.company.com',
            'tax_id': settings['business_gst']
        },
        'customer': {
            'name': 'John Anderson',
            'company': 'Anderson Industries Corp',
            'address': '456 Commerce Avenue',
            'city': 'New York, NY 10002',
            'phone': '+1 (555) 987-6543',
            'email': 'john@anderson.com'
        },
        'items': [
            {
                'code': 'SKU-001',
                'description': 'Professional Business Services - Annual Package',
                'qty': 1,
                'unit_price': '$2,500.00',
                'discount': '$0.00',
                'tax': '$200.00',
                'total': '$2,700.00'
            },
            {
                'code': 'SKU-002',
                'description': 'Premium Software License - 12 Months',
                'qty': 3,
                'unit_price': '$450.00',
                'discount': '-$135.00',
                'tax': '$94.50',
                'total': '$1,409.50'
            }
        ],
        'subtotal': '$5,150.00',
        'discount': '-$315.00',
        'tax': '$386.80',
        'total': '$5,221.80',
        'paid_amount': '$0.00',
        'balance_due': '$5,221.80'
    }
    
    return render_template('invoices/invoice_a4.html', **sample_data)


@invoices_bp.route('/preview/a5', methods=['GET'])
def preview_a5_invoice():
    """Preview A5 invoice template with sample data"""
    settings = get_receipt_settings()
    
    sample_data = {
        'invoice_number': 'INV-26-1234',
        'invoice_date': datetime.now().strftime('%m/%d/%y'),
        'due_date': (datetime.now() + timedelta(days=30)).strftime('%m/%d/%y'),
        'company': {
            'logo': 'LOGO',
            'name': settings['company_name'],
            'address': settings['business_address'],
            'city': settings['business_city'],
            'phone': settings['business_phone'],
            'tax_id': settings['business_gst']
        },
        'customer': {
            'name': 'John Anderson',
            'company': 'Anderson Industries',
            'address': '456 Commerce Ave',
            'city': 'New York, NY 10002'
        },
        'items': [
            {
                'code': 'SKU-001',
                'description': 'Professional Business Services',
                'qty': 1,
                'amount': '$2,500.00',
                'total': '$2,700.00'
            },
            {
                'code': 'SKU-002',
                'description': 'Software License - 12 Months',
                'qty': 3,
                'amount': '$450.00',
                'total': '$1,409.50'
            }
        ],
        'subtotal': '$5,150.00',
        'discount': '-$315.00',
        'tax': '$386.80',
        'total_due': '$5,221.80',
        'balance_due': '$5,221.80'
    }
    
    return render_template('invoices/invoice_a5.html', **sample_data)


@invoices_bp.route('/preview/receipt', methods=['GET'])
def preview_thermal_receipt():
    """Preview 80mm thermal receipt template with sample data"""
    settings = get_receipt_settings()
    
    sample_data = {
        'receipt_number': '0001234',
        'receipt_date': datetime.now().strftime('%m/%d/%Y'),
        'receipt_time': datetime.now().strftime('%H:%M:%S'),
        'cashier': 'John Smith',
        'company_name': settings['company_name'],
        'company_address': settings['business_address'],
        'company_phone': settings['business_phone'],
        'company_email': settings.get('business_email', ''),
        'customer_name': 'Walk-In Customer',
        'invoice_number': 'INV-2026-4567',
        'items': [
            {
                'qty': '2',
                'description': 'Premium Item #1',
                'code': 'SKU-001',
                'price': '$25.00',
                'total': '$50.00'
            },
            {
                'qty': '1',
                'description': 'Service Package',
                'code': 'SVC-002',
                'price': '$75.00',
                'total': '$75.00'
            },
            {
                'qty': '3',
                'description': 'Retail Product',
                'code': 'SKU-003',
                'price': '$10.50',
                'total': '$31.50'
            },
            {
                'qty': '1',
                'description': 'Professional Service',
                'code': 'SVC-004',
                'price': '$45.00',
                'total': '$45.00'
            }
        ],
        'subtotal': '$201.50',
        'discount': '-$10.08',
        'tax': '$15.31',
        'delivery_fee': '$5.00',
        'total': '$211.73',
        'paid': '$211.73',
        'change': '$0.00',
        'payment_method': 'CARD',
        'reference': '123456789012',
        'authorization': 'APPROVED',
        'thank_you': f'{settings["thank_you_message"].split("!")[0]}!' if settings.get("thank_you_message") else "THANK YOU!",
        'thank_you_message': settings.get('thank_you_message', 'For your patronage and support'),
        'warranty_info': settings.get('warranty_info', ''),
        'footer_text': settings.get('footer_text', '')
    }
    
    return render_template('invoices/thermal_receipt_80mm.html', **sample_data)


@invoices_bp.route('/template/a4', methods=['GET'])
def get_a4_template():
    """Get A4 invoice HTML template"""
    with open('app/templates/invoices/invoice_a4.html', 'r') as f:
        return f.read()


@invoices_bp.route('/template/a5', methods=['GET'])
def get_a5_template():
    """Get A5 invoice HTML template"""
    with open('app/templates/invoices/invoice_a5.html', 'r') as f:
        return f.read()


@invoices_bp.route('/template/receipt', methods=['GET'])
def get_receipt_template():
    """Get 80mm thermal receipt HTML template"""
    with open('app/templates/invoices/thermal_receipt_80mm.html', 'r') as f:
        return f.read()


@invoices_bp.route('/template/styles', methods=['GET'])
def get_print_styles():
    """Get print optimization CSS"""
    with open('app/templates/invoices/print_styles.css', 'r') as f:
        return f.read(), 200, {'Content-Type': 'text/css'}


@invoices_bp.route('/api/settings', methods=['GET'])
def get_settings_api():
    """Get current receipt settings as JSON"""
    try:
        settings = get_receipt_settings()
        return jsonify({'success': True, 'settings': settings})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@invoices_bp.route('/api/settings', methods=['POST'])
def save_settings_api():
    """Save receipt settings to database"""
    if not current_user.is_authenticated:
        return jsonify({'error': 'Not authenticated'}), 401
    
    try:
        from app.utils.company import get_current_company
        company = get_current_company()
        company_id = company.id if company else None
        
        current_app.logger.info(f"Saving receipt settings for company_id: {company_id}")
        
        data = request.get_json()
        current_app.logger.info(f"Received settings data: {list(data.keys())}")
        
        # Map form keys to database keys
        key_mapping = {
            'company_name': 'business_name',  # Map company_name to business_name for consistency
            'business_address': 'business_address',
            'business_city': 'business_city',
            'business_phone': 'business_phone',
            'business_email': 'business_email',
            'business_gst': 'business_gst',
            'thank_you_message': 'thank_you_message',
            'warranty_info': 'warranty_info',
            'footer_text': 'footer_text',
            'receipt_logo': 'receipt_logo',
            'default_receipt_format': 'default_receipt_format',
            'show_qr_code': 'show_qr_code',
            'receipt_type': 'receipt_type'
        }
        
        saved_count = 0
        for form_key, db_key in key_mapping.items():
            if form_key in data:
                value_str = str(data[form_key])
                current_app.logger.info(f"Saving {form_key} as {db_key}={value_str}")
                
                # Check if setting exists
                existing = Setting.query.filter_by(
                    setting_category='receipt',
                    setting_key=db_key,
                    company_id=company_id
                ).first()
                
                if existing:
                    existing.setting_value = value_str
                    existing.updated_at = datetime.now()
                    current_app.logger.info(f"Updated existing setting: {db_key}")
                else:
                    new_setting = Setting(
                        setting_category='receipt',
                        setting_key=db_key,
                        setting_value=value_str,
                        company_id=company_id
                    )
                    db.session.add(new_setting)
                    current_app.logger.info(f"Created new setting: {db_key}")
                
                saved_count += 1
        
        db.session.commit()
        current_app.logger.info(f"Successfully saved {saved_count} receipt settings")
        
        # Get updated settings
        updated_settings = get_receipt_settings(company_id)
        current_app.logger.info(f"Retrieved updated settings after save")
        
        return jsonify({
            'success': True,
            'message': f'Receipt settings saved successfully ({saved_count} items)',
            'settings': updated_settings
        })
    
    except Exception as e:
        db.session.rollback()
        current_app.logger.error(f"Error saving settings: {str(e)}", exc_info=True)
        return jsonify({'error': str(e)}), 500


@invoices_bp.route('/api/generate', methods=['POST'])
def generate_invoice_api():
    """
    API endpoint to generate invoice HTML
    
    Request body:
    {
        "format": "a4" | "a5" | "thermal",
        "invoice_data": { invoice object }
    }
    """
    try:
        data = request.get_json()
        format_type = data.get('format', 'a4').lower()
        invoice_data = data.get('invoice_data', {})
        
        if format_type == 'a4':
            html = render_template('invoices/invoice_a4.html', **invoice_data)
        elif format_type == 'a5':
            html = render_template('invoices/invoice_a5.html', **invoice_data)
        elif format_type == 'thermal':
            html = render_template('invoices/thermal_receipt_80mm.html', **invoice_data)
        else:
            return jsonify({'error': 'Invalid format. Use: a4, a5, or thermal'}), 400
        
        return jsonify({
            'success': True,
            'format': format_type,
            'html': html
        })
    
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@invoices_bp.route('/api/sample/<format_type>', methods=['GET'])
def get_sample_data(format_type):
    """Get sample data for a given format"""
    
    samples = {
        'a4': {
            'invoice_number': 'INV-2026-001234',
            'invoice_date': datetime.now().strftime('%m/%d/%Y'),
            'due_date': (datetime.now() + timedelta(days=30)).strftime('%m/%d/%Y'),
            'company': {
                'name': 'Your Company Name',
                'address': '123 Business Street, Suite 100',
                'city': 'New York, NY 10001',
                'phone': '+1 (555) 123-4567',
                'email': 'billing@company.com',
                'tax_id': '12-3456789'
            },
            'customer': {
                'name': 'Customer Name',
                'company': 'Customer Company',
                'address': '456 Commerce Avenue',
                'city': 'New York, NY 10002'
            },
            'items': [
                {
                    'code': 'SKU-001',
                    'description': 'Product Description',
                    'qty': 1,
                    'unit_price': '$100.00',
                    'discount': '$0.00',
                    'tax': '$8.00',
                    'total': '$108.00'
                }
            ]
        },
        'a5': {
            'invoice_number': 'INV-26-1234',
            'invoice_date': datetime.now().strftime('%m/%d/%y'),
            'due_date': (datetime.now() + timedelta(days=30)).strftime('%m/%d/%y'),
            'company': {'name': 'Your Company'},
            'customer': {'name': 'Customer Name'},
            'items': [
                {
                    'code': 'SKU-001',
                    'description': 'Product',
                    'qty': 1,
                    'amount': '$100.00',
                    'total': '$108.00'
                }
            ]
        },
        'thermal': {
            'receipt_number': '0001234',
            'receipt_date': datetime.now().strftime('%m/%d/%Y'),
            'receipt_time': datetime.now().strftime('%H:%M:%S'),
            'company_name': 'YOUR STORE',
            'customer_name': 'Walk-In Customer',
            'items': [
                {
                    'code': 'SKU-001',
                    'description': 'Item',
                    'qty': 1,
                    'price': '$25.00',
                    'total': '$25.00'
                }
            ],
            'total': '$25.00'
        }
    }
    
    if format_type.lower() in samples:
        return jsonify(samples[format_type.lower()])
    else:
        return jsonify({'error': 'Invalid format'}), 404


@invoices_bp.route('/docs', methods=['GET'])
def documentation():
    """Display invoice template documentation"""
    with open('app/templates/invoices/README.md', 'r') as f:
        readme_content = f.read()
    
    return f"""
    <html>
        <head>
            <title>Invoice Templates Documentation</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; }}
                h1, h2, h3 {{ color: #0051ba; }}
                code {{ background: #f5f5f5; padding: 2px 6px; border-radius: 3px; }}
                pre {{ background: #f5f5f5; padding: 10px; border-radius: 5px; overflow-x: auto; }}
                table {{ border-collapse: collapse; width: 100%; margin: 10px 0; }}
                td, th {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #f0f0f0; }}
            </style>
        </head>
        <body>
            {readme_content}
        </body>
    </html>
    """


# Error handlers

@invoices_bp.errorhandler(404)
def not_found(error):
    """Handle 404 errors"""
    return jsonify({'error': 'Endpoint not found'}), 404


@invoices_bp.errorhandler(500)
def internal_error(error):
    """Handle 500 errors"""
    return jsonify({'error': 'Internal server error'}), 500


# Helper functions for integration with existing routes

def register_invoice_routes(app):
    """Register invoice blueprint with Flask app"""
    app.register_blueprint(invoices_bp)


# Export routes
__all__ = ['invoices_bp', 'register_invoice_routes']
